config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  after_create_commit :broadcast_chat

  def broadcast_chat
    broadcast_append_to(:chats, target: "chats", partial: "chats/chat", locals: { chat: self })
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :chat
  after_create_commit :broadcast_message
  after_update_commit :broadcast_update_message
  
  def broadcast_update_message
    broadcast_replace_to dom_id(chat, :messages), target: dom_id(self), partial: "messages/message", locals: { message: self }
  end

  def broadcast_message
    broadcast_append_to dom_id(chat, :messages), target: "chat-messages", partial: "messages/message", locals: { message: self }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @chat = Chat.find(params[:id])
  end
  def index
    @chats = Chat.all
  end
  def create
    @chat = Chat.create
    redirect_to @chat
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat

  def new
    @message = @chat.messages.new
  end  

  def create
    @message = @chat.messages.build(message_params)
    if @message.save
      GetAiResponseJob.perform_later(@message.chat_id, @message.content)
      redirect_to new_message_path(chat_id: @chat.id), notice: 'Message was successfully created.'
    else
      render :new
    end
  end

  def index
    @messages = @chat.messages
  end

  private

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def message_params
    params.require(:message).permit(:content, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/_chat.html.erb
<%= link_to chat, data: { turbo_frame: :chat } do %>
<div class="w-full text-gray-100 hover:text-green-500">
  <%= chat&.messages&.first&.content || "New AI chat conversation" %>
</div>
<% end %>

app/views/chats/index.html.erb
<style>
  body {
    background-color: black;
  }
</style>
<div class="flex w-full">
<%= turbo_stream_from :chats %>
<div class="max-w-sm w-full h-full flex flex-col gap-4 p-2 w-full flex-shrink-0 bg-[#2e2e2e] rounded-lg" id="chats">
  <%= link_to  chats_path, data: { turbo_method: :post, turbo_frame: :chat }, class: "flex gap-2 justify-center items-center bg-gray-500 text-gray-100 rounded-lg p-2 text-center mr-auto" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
    </svg>
    <span> Create Chat </span>
  <% end %>
  <% @chats.each do |chat| %>
    <%= render "chat", chat: chat %>
  <% end %>
</div>
<div class="w-full ml-4">
  <%= turbo_frame_tag :chat, src: ( chat_path(@chats.first) if @chats.any? )  %>
</div>
</div>

app/views/chats/show.html.erb
<%= turbo_frame_tag :chat do %>
<div class="flex flex-col w-full h-full">
  <%= turbo_stream_from(dom_id(@chat, :messages)) %>
  <%= turbo_frame_tag(:messages, src: messages_path(chat_id: @chat.id)) %>
  <%= turbo_frame_tag(:new_message, src: new_message_path(chat_id: @chat.id))  %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AiAppTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, class: "contents") do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :chat_id %>
    <%= form.text_field :chat_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :role %>
    <%= form.number_field :role, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div data-chat-message-target="message" id="<%= dom_id(message) %>" class="bg-gray-200 text-gray-900 shadow-lg p-4 rounded-lg">
  <%= message.content %>
</div>

app/views/messages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<%= turbo_frame_tag(:messages) do %> 
  <div data-controller="chat-message" class="w-full gap-4 flex flex-col h-[70vh] overflow-y-scroll" id="chat-messages">
    <%= render partial: "message", collection: @messages %>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag :new_message do %>
  <%= form_with model: @chat.messages.new, url: messages_path(chat_id: @chat.id) do |f| %>
   <div class="w-full flex items-center gap-2"> 
   <div class="flex flex-col w-full">
      <%= f.label :content, "What do you want to ask?" %>
      <%= f.text_area :content, class: "w-full" %>
    </div>
    <%= button_tag class: "mt-4 flex p-2 rounded-lg bg-gradient-to-r from-indigo-500 to-blue-500 text-blue-100 font-semibold" do %>
      Send Message
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" />
      </svg>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/messages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @message %>

    <%= link_to "Edit this message", edit_message_path(@message), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this message", @message, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>